export const ANAGRAM_POOL = [
  { w: "GALLETA", s: "L L A T E G A", f: ["GACELA", "GALLINA", "GALEON"] },
  { w: "CHOCOLATE", s: "L A T E C O C H O", f: ["CHICOTE", "COHETE", "CHALECO"] },
  { w: "CARAMELO", s: "L O M E R A C A", f: ["CAMARERO", "CALAMAR", "CARAVANA"] },
  { w: "PIRULETA", s: "T A L U R I P E", f: ["PULSERA", "PUPITRE", "PILOTO"] },
  { w: "PASTEL", s: "T E L P A S", f: ["POSTRE", "PATIN", "PALETA"] },
  { w: "BOMBÓN", s: "B O N M O M", f: ["BOTON", "BALON", "BOMBA"] },
  { w: "VAINILLA", s: "L I L A N A I V", f: ["VALIENTE", "VAJILLA", "VAPOR"] },
  { w: "FRESA", s: "S A E F R", f: ["FIESTA", "FAROLA", "FUEGO"] },
  { w: "LIMÓN", s: "N O M I L", f: ["LION", "LISTON", "LAPIZ"] },
  { w: "PLATANO", s: "T A N O P L A", f: ["PLATERO", "PALMERA", "PLATINO"] },
  { w: "MANZANA", s: "Z A N A N A M", f: ["MANZANILLA", "MARRANO", "MANERA"] },
  { w: "NARANJA", s: "J A N A R N A", f: ["NAVAJA", "NATILLAS", "NAVACERRADA"] },
  { w: "CEREZA", s: "Z A R E E C", f: ["CERVEZA", "CABEZA", "CORTEZA"] },
  { w: "ALMENDRA", s: "N D R A A L M E", f: ["ALFOMBRA", "ALMENARA", "ALMOHADA"] },
  { w: "AVELLANA", s: "L L A N A V E A", f: ["ALABANZA", "AVELLANEDA", "AVISPA"] },
  { w: "NUEZ", s: "E Z U N", f: ["NARIZ", "NIEVE", "NUBE"] },
  { w: "PISTACHO", s: "T A C H O P I S", f: ["PINCHO", "PESCADO", "PICNIC"] },
  { w: "CANELA", s: "L A N E C A", f: ["CADENA", "CAPILLA", "CAMISA"] },
  { w: "AZÚCAR", s: "C A R Z U A", f: ["AZULEJO", "AZOTEA", "AGUJA"] },
  { w: "MIEL", s: "L E I M", f: ["MESA", "MINA", "MURO"] },
  { w: "HELADO", s: "D O L A H E", f: ["HERIDO", "HUEVO", "HUERTO"] },
  { w: "CUPCAKE", s: "P C A K E C U", f: ["CUBETA", "CORTES", "CUMBRE"] },
  { w: "DONUT", s: "T U N O D", f: ["DUCHA", "DIENTE", "DARDO"] },
  { w: "MERENGUE", s: "N G U E R E M E", f: ["MANGUERA", "MENDRUGO", "MENTIRA"] },
  { w: "GOMINOLA", s: "N O L A M I G O", f: ["GONDOLA", "GORILA", "GOTERA"] },
  { w: "REGALIZ", s: "L I Z A G E R", f: ["REGALO", "RELOJ", "REFLEJO"] },
  { w: "BIZCOCHO", s: "C H O Z O B I C", f: ["BOCADO", "BOCETO", "BICHITO"] },
  { w: "FLAN", s: "L A N F", f: ["FLOR", "FARO", "FOCA"] },
  { w: "NATILLAS", s: "L L A S T I N A", f: ["NOTICIAS", "NAVAJAS", "NOVELAS"] },
  { w: "CHURRO", s: "R R O C H U", f: ["CHARCO", "CHORRO", "CHOPO"] },
  { w: "BUÑUELO", s: "Ñ U E L O B U", f: ["BUEY", "BURRO", "BOTIJA"] },
  { w: "TORTITA", s: "T I T A R T O", f: ["TORTUGA", "TORMENTA", "TORTILLA"] },
  { w: "GOFRE", s: "F R E G O", f: ["GOTA", "GRIFO", "GORRO"] },
  { w: "CREPE", s: "P E E R C", f: ["COPA", "CRUZ", "CLAVO"] },
  { w: "TURRÓN", s: "R O N T U R", f: ["TORONJA", "TRUCO", "TORO"] },
  { w: "MAZAPÁN", s: "Z A P A N M A", f: ["MANZANA", "MADRUGADA", "MANADA"] },
  { w: "POLVORÓN", s: "R O N V O L P O", f: ["POLVORA", "POLICIA", "PALOMAR"] },
  { w: "TRUFA", s: "F A R T U", f: ["TUMBA", "TROPA", "TURBA"] },
  { w: "ALFALFA", s: "L F A L A A F", f: ["ALBACA", "ALCALDE", "ALACRAN"] },
  { w: "BARQUILLO", s: "L L I Q U O B A R", f: ["BARCO", "BARRIL", "BARAJA"] },
  { w: "CROISSANT", s: "S A N T C R O I S", f: ["CRISTAL", "CRONICA", "COSTURA"] },
  { w: "HOJALDRE", s: "J A L D R E H O", f: ["HOJALATA", "HORNO", "HORQUETA"] },
  { w: "MANTEQUILLA", s: "L L A Q U I T E M A N", f: ["MANTECA", "MANTON", "MANTEL"] },
  { w: "MERMELADA", s: "L A D A M E R M E", f: ["MEMORIA", "MEDALLA", "MERCADO"] },
  { w: "NOCILLA", s: "L L A C I N O", f: ["NOTICIA", "NOVELA", "NIEBLA"] },
  { w: "YOGUR", s: "G U R Y O", f: ["YEGUA", "YODO", "YATE"] },
  { w: "BATIDO", s: "T I D O B A", f: ["BOTELLA", "BANDERA", "BOCADILLO"] },
  { w: "ZUMO", s: "M O Z U", f: ["ZORRO", "ZAPATO", "ZONA"] },
  { w: "HORCHATA", s: "C H A T A R H O", f: ["HORQUETA", "HOSPITAL", "HORTELANO"] },
  { w: "GRANIZADO", s: "N I Z A D O G R A", f: ["GRANERO", "GRANADA", "GRAMATICA"] },
  { w: "SORBETE", s: "B E T E R S O", f: ["SOMBRERO", "SOBRE", "SONRISA"] },
  { w: "POLO", s: "L O P O", f: ["PATO", "PELO", "PITO"] },
  { w: "CUCURUCHO", s: "R U C H O C U C U", f: ["CUCHARA", "CUBIERTO", "CUERPO"] },
  { w: "PALMERA", s: "M E R A P A L", f: ["PALOMA", "PALABRA", "PALETA"] },
  { w: "ENSAIMADA", s: "I M A D A E N S A", f: ["ENSALADA", "ENSAYO", "ENTRADA"] },
  { w: "SOBAO", s: "B A O S O", f: ["SOPA", "SOLO", "SELLO"] },
  { w: "ROSQUILLA", s: "L L A Q U I R O S", f: ["ROSA", "RODILLO", "ROQUEDAL"] },
  { w: "MAGDALENA", s: "D A L E N A M A G", f: ["MADRINA", "MARGARITA", "MANZANILLA"] },
  { w: "MACARRÓN", s: "R R O N C A M A", f: ["MARCADOR", "MADRUGADA", "MALETIN"] },
  { w: "TARTA", s: "R T A T A", f: ["TAZA", "TORRE", "TELA"] },
  { w: "PAN", s: "N A P", f: ["PIE", "PEZ", "PAZ"] },
  { w: "QUESO", s: "S O E Q U", f: ["QUEMA", "QUIJADA", "QUIOSCO"] },
  { w: "LECHE", s: "C H E E L", f: ["LENTEJA", "LECHUGA", "LEON"] },
  { w: "CAFÉ", s: "F E A C", f: ["CAMA", "CASA", "CABRA"] },
  { w: "TÉ", s: "E T", f: ["FE", "SOL", "MAR"] },
  { w: "INFUSIÓN", s: "F U S I O N N I", f: ["ILUSION", "INVASION", "INDUCCION"] },
  { w: "JARABE", s: "R A B E J A", f: ["JARDIN", "JAULA", "JAMON"] },
  { w: "GOLOSINA", s: "L O S I N A G O", f: ["GALLINA", "GAVIOTA", "GUITARRA"] },
  { w: "CARAMELITO", s: "M E L I T O C A R A", f: ["CALENDARIO", "CAMPESINO", "CARNICERO"] },
  { w: "DULCE", s: "L C E U D", f: ["DIENTE", "DEDO", "DADO"] },
  { w: "SALADO", s: "L A D O S A", f: ["SALMON", "SALUDO", "SARTEN"] },
  { w: "ÁCIDO", s: "C I D O A", f: ["ANILLO", "AVION", "ARBOL"] },
  { w: "AMARGO", s: "R G O A M A", f: ["AMIGO", "ABRIGO", "ARMARIO"] },
  { w: "SABROSO", s: "B R O S O S A", f: ["SOBRINO", "SOMBRA", "SILBATO"] },
  { w: "DELICIOSO", s: "L I C I O S O D E", f: ["DELICADO", "DELIRIO", "DESIERTO"] },
  { w: "CRUJIENTE", s: "J I E N T E C R U", f: ["CORRIENTE", "CREYENTE", "CRUCIFIJO"] },
  { w: "ESPONJOSO", s: "P O N J O S O E S", f: ["ESPEJISMO", "ESPADA", "ESPINACA"] },
  { w: "CREMOSO", s: "M O S O R E C", f: ["CAMINO", "CASTILLO", "CORONA"] },
  { w: "GLASEADO", s: "S E A D O G L A", f: ["GRANADO", "GUSTOSO", "GALOPANTE"] },
  { w: "FONDANT", s: "D A N T F O N", f: ["FRONTAL", "FUENTE", "FOSFORO"] },
  { w: "SIROPE", s: "R O P E S I", f: ["SIRENA", "SILENCIO", "SOBRE"] },
  { w: "TOPPING", s: "P P I N G T O", f: ["TAPON", "TORPEDO", "TOLDO"] },
  { w: "VIRUTAS", s: "R U T A S V I", f: ["VENTANAS", "VIOLETAS", "VECINAS"] },
  { w: "CACAHUETE", s: "H U E T E C A C A", f: ["CAMISETA", "CARRETERA", "CACHORRO"] },
  { w: "NUEZCARAMELO", s: "Z C A R A M E L O N U E", f: ["NOTICIARIO", "NACIMIENTO", "NATURALEZA"] },
  { w: "COCO", s: "C O O C", f: ["CODO", "CONO", "CORO"] },
  { w: "PIÑA", s: "Ñ A I P", f: ["PALA", "PICO", "PISA"] },
  { w: "MANGO", s: "G O M A N", f: ["MANTA", "MONO", "MURO"] },
  { w: "MELÓN", s: "L O N E M", f: ["MOTOR", "MOLINO", "MUSEO"] },
  { w: "SANDÍA", s: "D I A N S A", f: ["SARDINA", "SALIDA", "SEMILLA"] },
  { w: "MELOCOTÓN", s: "L O C O T O N M E", f: ["MONASTERIO", "MONUMENTO", "MARINERO"] },
  { w: "ALBARICOQUE", s: "R I C O Q U E A L B A", f: ["ALBERGUE", "ALMANAQUE", "ALMIRANTE"] },
  { w: "CIRUELA", s: "R U E L A C I", f: ["CIGARRA", "CINTURA", "CIUDAD"] },
  { w: "HIGO", s: "G O I H", f: ["HIJO", "HILO", "HOJA"] },
  { w: "UVA", s: "V A U", f: ["UNO", "UNA", "USO"] },
  { w: "FRAMBUESA", s: "M B U E S A F R A", f: ["FRAGANCIA", "FRACTURA", "FRONTERA"] },
  { w: "ARÁNDANO", s: "R A N D A N O A", f: ["ARMARIO", "ARTISTA", "ALUMNO"] },
  { w: "MORA", s: "R A M O", f: ["MESA", "MINA", "MULA"] },
  { w: "GROSELLA", s: "S E L L A G R O", f: ["GRANADA", "GRIETA", "GRUTA"] },
  { w: "KIWI", s: "W I K I", f: ["KILO", "KUNGFU", "KAYAK"] }
];

/**
 * 100 CASOS DE ANTÓNIMOS
 */
export const ANTONYMS_POOL = [
  { w: "VALIENTE", c: "COBARDE", f: ["FUERTE", "AUDAZ", "TEMERARIO"] },
  { w: "GIGANTE", c: "DIMINUTO", f: ["COLOSAL", "ENORME", "PESADO"] },
  { w: "PACIENCIA", c: "PRISA", f: ["CALMA", "SERENIDAD", "ESPERA"] },
  { w: "ABUNDANCIA", c: "ESCASEZ", f: ["RIQUEZA", "PLENITUD", "EXCESO"] },
  { w: "CONFUNDIR", c: "ACLARAR", f: ["ENREDAR", "DUDAR", "MEZCLAR"] },
  { w: "ANCHO", c: "ESTRECHO", f: ["ESPACIOSO", "AMPLIO", "GRANDE"] },
  { w: "RÍGIDO", c: "FLEXIBLE", f: ["DURO", "FIRME", "SÓLIDO"] },
  { w: "COMPLEJO", c: "SIMPLE", f: ["DIFÍCIL", "ENREVESADO", "OSCURO"] },
  { w: "LÚCIDO", c: "CONFUSO", f: ["CLARO", "BRILLANTE", "DESPIERTO"] },
  { w: "OPTIMISTA", c: "PESIMISTA", f: ["ALEGRE", "POSITIVO", "CONFIADO"] },
  { w: "EFÍMERO", c: "DURADERO", f: ["FUGAZ", "BREVE", "PASAJERO"] },
  { w: "GENEROSO", c: "TACAÑO", f: ["BONDADOSO", "DESPRENDIDO", "AMABLE"] },
  { w: "AUDAZ", c: "PRUDENTE", f: ["VALEROSO", "INTREPIDO", "OSADO"] },
  { w: "CÁLIDO", c: "GÉLIDO", f: ["TEMPLADO", "CALIENTE", "SUAVE"] },
  { w: "LENTO", c: "VELOZ", f: ["PAUSADO", "CALMADO", "PESADO"] },
  { w: "MODESTO", c: "SOBERBIO", f: ["HUMILDE", "SENCILLO", "RESERVADO"] },
  { w: "DENSO", c: "LIGERO", f: ["ESPESO", "COMPACTO", "PESADO"] },
  { w: "OPACO", c: "TRANSPARENTE", f: ["OSCURO", "SOMBRÍO", "TURBIO"] },
  { w: "RUIDOSO", c: "SILENCIOSO", f: ["ESTRUENDOSO", "BULLICIOSO", "SONORO"] },
  { w: "BRUSCO", c: "SUAVE", f: ["ÁSPERO", "TOSCO", "REPENTINO"] },
  { w: "ERUDITO", c: "IGNORANTE", f: ["SABIO", "CULTO", "LETRADO"] },
  { w: "SERENO", c: "AGITADO", f: ["TRANQUILO", "PACÍFICO", "QUIETO"] },
  { w: "PUNTUAL", c: "TARDÍO", f: ["EXACTO", "CUMPLIDOR", "FORMAL"] },
  { w: "NÍTIDO", c: "BORROSO", f: ["CLARO", "PRECISO", "DEFINIDO"] },
  { w: "TOLERANTE", c: "INTRANSIGENTE", f: ["COMPRENSIVO", "PACIENTE", "FLEXIBLE"] },
  { w: "REBELDE", c: "DÓCIL", f: ["DESOBEDIENTE", "INSURGENTE", "INDÓMITO"] },
  { w: "LEAL", c: "TRAIDOR", f: ["FIEL", "NOBLE", "SINCERO"] },
  { w: "FRÁGIL", c: "RESISTENTE", f: ["QUEBRADIZO", "DÉBIL", "DELICADO"] },
  { w: "AMISTOSO", c: "HOSTIL", f: ["CORDIAL", "AFABLE", "CERCANO"] },
  { w: "PROFUNDO", c: "SUPERFICIAL", f: ["HONDO", "PENETRANTE", "ABISMAL"] },
  { w: "RICO", c: "POBRE", f: ["PULPUDO", "ABUNDANTE", "SABROSO"] },
  { w: "CLARO", c: "OSCURO", f: ["LUMINOSO", "TRANSPARENTE", "BLANCO"] },
  { w: "ALTO", c: "BAJO", f: ["ELEVADO", "GRANDE", "SUPERIOR"] },
  { w: "FUERTE", c: "DÉBIL", f: ["ROBUSTO", "VIGOROSO", "DURO"] },
  { w: "JOVEN", c: "VIEJO", f: ["NUEVO", "FRESCO", "INFANTIL"] },
  { w: "SECO", c: "MOJADO", f: ["ÁRIDO", "DESHIDRATADO", "ASPERO"] },
  { w: "LLENO", c: "VACÍO", f: ["REPUDO", "COMPLETO", "COLMADO"] },
  { w: "VERDAD", c: "MENTIRA", f: ["CERTEZA", "REALIDAD", "HECHO"] },
  { w: "AMOR", c: "ODIO", f: ["CARIÑO", "PASIÓN", "AFECTO"] },
  { w: "PAZ", c: "GUERRA", f: ["CALMA", "SOSIEGO", "ARMONÍA"] },
  { w: "ALEGRÍA", c: "TRISTEZA", f: ["GOZO", "FELICIDAD", "ENTUSIASMO"] },
  { w: "DULCE", c: "AMARGO", f: ["SUAVE", "AZUCARADO", "GOLOSO"] },
  { w: "LIMPIO", c: "SUCIO", f: ["PULCRO", "ASEADO", "IMPECABLE"] },
  { w: "DURO", c: "BLANDO", f: ["FIRME", "SÓLIDO", "RESISTENTE"] },
  { w: "FÁCIL", c: "DIFÍCIL", f: ["SENCILLO", "CÓMODO", "ACCESIBLE"] },
  { w: "BELLO", c: "FEO", f: ["HERMOSO", "BONITO", "LINDO"] },
  { w: "SANO", c: "ENFERMO", f: ["SALUDABLE", "VITAL", "FUERTE"] },
  { w: "CORRECTO", c: "ERRÓNEO", f: ["ACERTADO", "JUSTO", "EXACTO"] },
  { w: "ABIERTO", c: "CERRADO", f: ["DESPEJADO", "FRANCO", "DISPONIBLE"] },
  { w: "PESADO", c: "LIVIANO", f: ["GRANDE", "MOLESTO", "DENSO"] },
  { w: "VALIOSO", c: "INSIGNIFICANTE", f: ["PRECIOSO", "COSTOSO", "ÚTIL"] },
  { w: "CONOCIDO", c: "EXTRAÑO", f: ["FAMILIAR", "POPULAR", "CÉLEBRE"] },
  { w: "LEJOS", c: "CERCA", f: ["DISTANTE", "REMOTO", "APARTADO"] },
  { w: "GANAR", c: "PERDER", f: ["TRIUNFAR", "VENCER", "OBTENER"] },
  { w: "SUBIR", c: "BAJAR", f: ["ASCENDER", "ELEVAR", "TREPAR"] },
  { w: "ENTRAR", c: "SALIR", f: ["INGRESAR", "ACCEDER", "PENETRAR"] },
  { w: "UNIR", c: "SEPARAR", f: ["JUNTAR", "CONECTAR", "PEGAR"] },
  { w: "CREAR", c: "DESTRUIR", f: ["INVENTAR", "FABRICAR", "GENERAR"] },
  { w: "RECORDAR", c: "OLVIDAR", f: ["MEMORIZAR", "EVOCAR", "RETENER"] },
  { w: "PRENDER", c: "APAGAR", f: ["ENCENDER", "ACTIVAR", "INICIAR"] },
  { w: "COMPRAR", c: "VENDER", f: ["ADQUIRIR", "PAGAR", "LOGRAR"] },
  { w: "ACEPTAR", c: "RECHAZAR", f: ["ADMITIR", "TOLERAR", "ASUMIR"] },
  { w: "REÍR", c: "LLORAR", f: ["SONREÍR", "FESTEJAR", "GOZAR"] },
  { w: "VIVIR", c: "MORIR", f: ["HABITAR", "EXISTIR", "CRECER"] },
  { w: "HABLAR", c: "CALLAR", f: ["DECIR", "CHARLAR", "EXPRESAR"] },
  { w: "DORMIR", c: "DESPERTAR", f: ["DESCANSAR", "REPOSAR", "SOÑAR"] },
  { w: "DAR", c: "RECIBIR", f: ["ENTREGAR", "OFRECER", "DONAR"] },
  { w: "TRIUNFO", c: "DERROTA", f: ["ÉXITO", "VICTORIA", "LAUREL"] },
  { w: "PREMIO", c: "CASTIGO", f: ["GALARDÓN", "RECOMPENSA", "TROFEO"] },
  { w: "SALIDA", c: "LLEGADA", f: ["PARTIDA", "ESCAPE", "PUERTA"] },
  { w: "CALOR", c: "FRÍO", f: ["BOCHORNO", "TEMPERATURA", "FUEGO"] },
  { w: "LUZ", c: "TINIEBLA", f: ["BRILLO", "CLARIDAD", "ILUMINACIÓN"] },
  { w: "ORDEN", c: "CAOS", f: ["MÉTODO", "ARREGLO", "CONTROL"] },
  { w: "SILENCIO", c: "RUIDO", f: ["CALMA", "MUTISMO", "PAZ"] },
  { w: "RIQUEZA", c: "POBREZA", f: ["FORTUNA", "CAPITAL", "DINERO"] },
  { w: "SALUD", c: "ENFERMEDAD", f: ["BIENESTAR", "VIGOR", "FUERZA"] },
  { w: "CERTEZA", c: "DUDA", f: ["SEGURIDAD", "VERDAD", "CONVICCIÓN"] },
  { w: "LIBERTAD", c: "PRISIÓN", f: ["AUTONOMÍA", "INDEPENDENCIA", "ALBEDRÍO"] },
  { w: "JUSTICIA", c: "INEQUITAT", f: ["RECTITUD", "EQUIDAD", "LEYES"] },
  { w: "HONESTO", c: "CORRUPTO", f: ["ÍNTEGRO", "RECTO", "HONRADO"] },
  { w: "BRILIANTE", c: "APAGADO", f: ["RADIANTE", "LUCIDO", "DESTACADO"] },
  { w: "TRANQUILO", c: "NERVIOSO", f: ["PACÍFICO", "QUIETO", "SERENO"] },
  { w: "DISCRETO", c: "INDISCRETO", f: ["PRUDENTE", "RESERVADO", "CAUTO"] },
  { w: "ÁGIL", c: "TORPE", f: ["RÁPIDO", "VELOZ", "DESTRO"] },
  { w: "CÓMODO", c: "INCÓMODO", f: ["CONFORTABLE", "AGRADABLE", "FÁCIL"] },
  { w: "MODERNO", c: "ANTIGUO", f: ["ACTUAL", "NOVEDOSO", "RECIENTE"] },
  { w: "AMABLE", c: "DESAGRADABLE", f: ["CORDIAL", "ATENTO", "EDUCADO"] },
  { w: "SEGURA", c: "PELIGROSA", f: ["PROTEGIDA", "FIABLE", "FIRME"] },
  { w: "ÚTIL", c: "INÚTIL", f: ["PRÁCTICO", "EFICAZ", "VALIOSO"] },
  { w: "CLARA", c: "CONFUSA", f: ["EVIDENTE", "NÍTIDA", "TRANSPARENTE"] },
  { w: "VISÍVEL", c: "INVISIBLE", f: ["EVIDENTE", "PALPABLE", "NOTABLE"] },
  { w: "PACÍFICO", c: "VIOLENTO", f: ["TRANQUILO", "SERENO", "SOSEGADO"] },
  { w: "SINCERO", c: "HIPÓCRITA", f: ["HONESTO", "FRANCO", "VERAZ"] },
  { w: "PUNTUAL", c: "IMPUNTUAL", f: ["EXACTO", "FORMAL", "CUMPLIDOR"] },
  { w: "RESPETUOSO", c: "INSOLENTE", f: ["EDUCADO", "ATENTO", "CORRECTO"] },
  { w: "CURIOSO", c: "INDIFERENTE", f: ["INTERESADO", "INQUIETO", "ATENTO"] },
  { w: "OPTIMO", c: "PÉSIMO", f: ["EXCELENTE", "INMEJORABLE", "SUPERIOR"] },
  { w: "PERFECTO", c: "DEFECTUOSO", f: ["EXCELENTE", "IMPECABLE", "PULCRO"] },
  { w: "MADURO", c: "INMADURO", f: ["DESARROLLADO", "SENSATO", "LISTO"] },
  { w: "CENTRAL", c: "PERIFÉRICO", f: ["PRINCIPAL", "MEDIO", "NUCLEAR"] }
];

/**
 * 100 CASOS DE SINÓNIMOS
 */
export const SYNONYMS_POOL = [
  { w: "FELIZ", c: "CONTENTO", f: ["TRISTE", "ENFADADO", "CANSADO"] },
  { w: "RÁPIDO", c: "VELOZ", f: ["LENTO", "PESADO", "PAUSADO"] },
  { w: "BELLO", c: "HERMOSO", f: ["FEO", "HORRIBLE", "DESAGRADABLE"] },
  { w: "GRANDE", c: "ENORME", f: ["PEQUEÑO", "DIMINUTO", "CHICO"] },
  { w: "SABIO", c: "ERUDITO", f: ["IGNORANTE", "NECIO", "TORPE"] },
  { w: "CASA", c: "HOGAR", f: ["CALLE", "PUENTE", "BARCO"] },
  { w: "CAMINAR", c: "ANDAR", f: ["PARAR", "DORMIR", "SENTAR"] },
  { w: "MIRAR", c: "OBSERVAR", f: ["IGNORAR", "TAPAR", "CEGAR"] },
  { w: "ESCUCHAR", c: "OÍR", f: ["CALLAR", "HABLAR", "GRITAR"] },
  { w: "COMENZAR", c: "INICIAR", f: ["TERMINAR", "ACABAR", "CERRAR"] },
  { w: "FINALIZAR", c: "CONCLUIR", f: ["EMPEZAR", "ABRIR", "CREAR"] },
  { w: "DULCE", c: "AZUCARADO", f: ["SALADO", "AMARGO", "ÁCIDO"] },
  { w: "VALIENTE", c: "AUDAZ", f: ["COBARDE", "MEDROSO", "TÍMIDO"] },
  { w: "CALMA", c: "TRANQUILIDAD", f: ["NERVIOS", "PRISA", "CAOS"] },
  { w: "ALEGRÍA", c: "GOZO", f: ["PENA", "DOLOR", "LLANTO"] },
  { w: "TRISTEZA", c: "MELANCOLÍA", f: ["FIESTA", "RISA", "EUFORIA"] },
  { w: "AMABLE", c: "AFABLE", f: ["BRUSCO", "TOSCO", "ANTIPÁTICO"] },
  { w: "FÁCIL", c: "SENCILLO", f: ["DIFÍCIL", "COMPLEJO", "DURO"] },
  { w: "RICHO", c: "OPULENTO", f: ["POBRE", "HUMILDE", "ESCASA"] },
  { w: "POBRE", c: "HUMILDE", f: ["MILLONARIO", "PODEROSO", "LUJOSO"] },
  { w: "FUERTE", c: "ROBUSTO", f: ["DÉBIL", "BLANDO", "FRÁGIL"] },
  { w: "DELGADO", c: "FLACO", f: ["GORDO", "ANCHUROSO", "PESADO"] },
  { w: "AMIGO", c: "COMPAÑERO", f: ["ENEMIGO", "RIVAL", "ADVERSARIO"] },
  { w: "ENEMIGO", c: "RIVAL", f: ["SOCIO", "HERMANO", "ALIADO"] },
  { w: "BRILHO", c: "RESPLANDOR", f: ["OSCURIDAD", "SOMBRA", "APAGÓN"] },
  { w: "OSCURO", c: "TENEBROSO", f: ["CLARO", "RADIANTE", "LUMINOSO"] },
  { w: "LIMPIO", c: "PULCRO", f: ["SUCIO", "MANCHADO", "TURBIO"] },
  { w: "SUCIO", c: "MUGRIENTO", f: ["ASEADO", "LAVADO", "IMPECABLE"] },
  { w: "CLARO", c: "NÍTIDO", f: ["BORROSO", "CONFUSO", "OPACO"] },
  { w: "CARO", c: "COSTOSO", f: ["BARATO", "GRATIS", "REGALADO"] },
  { w: "BARATO", c: "ECONÓMICO", f: ["CARÍSIMO", "LUJOSO", "VALIOSO"] },
  { w: "ANTIGUO", c: "ARCAICO", f: ["MODERNO", "NUEVO", "ACTUAL"] },
  { w: "NUEVO", c: "NOVEDOSO", f: ["VIEJO", "GASTADO", "USADO"] },
  { w: "TRABAJO", c: "EMPLEO", f: ["OCIO", "DESCANSO", "VACACIÓN"] },
  { w: "PROFESOR", c: "DOCENTE", f: ["ALUMNO", "ESTUDIANTE", "APRENDIZ"] },
  { w: "ALUMNO", c: "DISCÍPULO", f: ["MAESTRO", "DIRECTOR", "TUTOR"] },
  { w: "MÉDICO", c: "DOCTOR", f: ["PACIENTE", "ENFERMO", "BOTICARIO"] },
  { w: "AUTOMÓVIL", c: "COCHE", f: ["BARCO", "AVIÓN", "TREN"] },
  { w: "BARCO", c: "EMBARCACIÓN", f: ["CAMIÓN", "MOTO", "BICI"] },
  { w: "AVIÓN", c: "AERONAVE", f: ["SUBMARINO", "TRANVÍA", "PATÍN"] },
  { w: "CAMINO", c: "SENDERO", f: ["PARED", "RÍO", "ABISMO"] },
  { w: "CIUDAD", c: "URBE", f: ["MONTE", "DESIERTO", "SELVA"] },
  { w: "PUEBLO", c: "ALDEA", f: ["METRÓPOLI", "CAPITAL", "NACIÓN"] },
  { w: "BOSQUE", c: "SELVA", f: ["PLAYA", "DUNA", "ASFALTO"] },
  { w: "FLOR", c: "PLANTA", f: ["PIEDRA", "HIERRO", "NUBE"] },
  { w: "ANIMAL", c: "BESTIA", f: ["ÁRBOL", "MINERAL", "OBJETO"] },
  { w: "COMIDA", c: "ALIMENTO", f: ["VENENO", "HAMBRE", "AYUNO"] },
  { w: "BEBIDA", c: "LÍQUIDO", f: ["PAN", "SOL", "FUEGO"] },
  { w: "AGUA", c: "LÍQUIDO", f: ["TIERRA", "HUMO", "POLVO"] },
  { w: "FUEGO", c: "LLAMA", f: ["HIELO", "NIEVE", "LLUVIA"] },
  { w: "VIENTO", c: "BRISA", f: ["CALMA", "VACÍO", "SUEÑO"] },
  { w: "LLUVIA", c: "PRECIPITACIÓN", f: ["SEQUÍA", "SOL", "CALOR"] },
  { w: "SOL", c: "ASTRO", f: ["SOMBRA", "NOCHE", "LUNA"] },
  { w: "LUNA", c: "SATÉLITE", f: ["DÍA", "LUZ", "RAYO"] },
  { w: "ESTRELLA", c: "LUCERO", f: ["HOJA", "MAR", "ROCA"] },
  { w: "MAR", c: "OCÉANO", f: ["TIERRA", "CONTINENTE", "BOSQUE"] },
  { w: "RÍO", c: "CAUCE", f: ["CHARCO", "LAGO", "POZO"] },
  { w: "MONTAÑA", c: "MONTE", f: ["VALLE", "LLANURA", "PRADERA"] },
  { w: "VALLE", c: "CUENCA", f: ["PICO", "CUMBRE", "COLINA"] },
  { w: "TIEMPO", c: "CLIMA", f: ["ESPACIO", "PESO", "COLOR"] },
  { w: "DINERO", c: "FORTUNA", f: ["DEUDA", "POBREZA", "VACÍO"] },
  { w: "CARTA", c: "EPÍSTOLA", f: ["LIBRO", "REVISTA", "PRENSA"] },
  { w: "LIBRO", c: "TOMO", f: ["CUADRO", "ESCULTURA", "DISCO"] },
  { w: "CANCION", c: "MELODÍA", f: ["SILENCIO", "GRITO", "RUIDO"] },
  { w: "BAILE", c: "DANZA", f: ["REPOSO", "PARADA", "SIESTA"] },
  { w: "PINTURA", c: "CUADRO", f: ["POESÍA", "NOVELA", "TEATRO"] },
  { w: "HISTORIA", c: "RELATO", f: ["CALLADA", "SECRETO", "OLVIDO"] },
  { w: "PREGUNTA", c: "INTERROGANTE", f: ["RESPUESTA", "SOLUCIÓN", "FINAL"] },
  { w: "RESPUESTA", c: "CONTESTACIÓN", f: ["DUDA", "PREGUNTA", "MISTERIO"] },
  { w: "PROBLEMA", c: "CONFLICTO", f: ["PAZ", "ÉXITO", "ACUERDO"] },
  { w: "SOLUCIÓN", c: "DESENLACE", f: ["ENREDO", "PROBLEMA", "TRABA"] },
  { w: "ÉXITO", c: "TRIUNFO", f: ["FRACASO", "DERROTA", "CAÍDA"] },
  { w: "FRACASO", c: "DERROTA", f: ["VICTORIA", "CORONA", "PREMIO"] },
  { w: "PREMIO", c: "GALARDÓN", f: ["MULTA", "CASTIGO", "SANCION"] },
  { w: "CASTIGO", c: "SANCIÓN", f: ["PREMIO", "REGALO", "FIESTA"] },
  { w: "REGALO", c: "OBSEQUIO", f: ["VENTA", "COBRO", "ROBO"] },
  { w: "FIESTA", c: "CELEBRACIÓN", f: ["DUELO", "FUNERAL", "TRISTEZA"] },
  { w: "JUEGO", c: "DIVERSIÓN", f: ["TRABAJO", "OBLIGACIÓN", "PESADUMBRE"] },
  { w: "REGLA", c: "NORMA", f: ["DESORDEN", "CAPRICHO", "LIBERTAD"] },
  { w: "CONSEJO", c: "SUGERENCIA", f: ["ORDEN", "IMPOSICIÓN", "MANDO"] },
  { w: "ORDEN", c: "MANDATO", f: ["RUEGO", "SÚPLICA", "CONSEJO"] },
  { w: "AYUDA", c: "AUXILIO", f: ["ESTORBO", "ABANDONO", "FRENO"] },
  { w: "PELIGRO", c: "RIESGO", f: ["SEGURIDAD", "PROTECCIÓN", "REFUGIO"] },
  { w: "SEGURIDAD", c: "PROTECCIÓN", f: ["AMENAZA", "ALARMA", "RIESGO"] },
  { w: "MIEDO", c: "TEMOR", f: ["VALOR", "CORAJE", "CALMA"] },
  { w: "CORAJE", c: "VALENTÍA", f: ["MIEDO", "COBARDÍA", "FUGA"] },
  { w: "DUDA", c: "INCERTIDUMBRE", f: ["CERTEZA", "SEGURIDAD", "VERDAD"] },
  { w: "VERDAD", c: "CERTEZA", f: ["ENGAÑO", "MENTIRA", "FICCIÓN"] },
  { w: "MENTIRA", c: "EMBUSTE", f: ["REALIDAD", "HECHO", "VERDAD"] },
  { w: "SECRETO", c: "MISTERIO", f: ["NOTICIA", "ANUNCIO", "VOZ"] },
  { w: "ESPERANZA", c: "ILUSIÓN", f: ["DESESPERO", "DESÁNIMO", "DESGANA"] },
  { w: "DESEO", c: "ANHELO", f: ["RECHAZO", "DESPRECIO", "DESINTERÉS"] },
  { w: "PENSAMIENTO", c: "IDEA", f: ["ACCION", "IMPULSO", "SUEÑO"] },
  { w: "SUEÑO", c: "ILUSIÓN", f: ["DESPIERTO", "VIGILIA", "REALIDAD"] },
  { w: "MEMORIA", c: "RECUERDO", f: ["OLVIDO", "AMNESIA", "VACÍO"] },
  { w: "OLVIDO", c: "DESCUIDO", f: ["MEMORIA", "ATENCIÓN", "REGISTRO"] },
  { w: "ATENCIÓN", c: "CUIDADO", f: ["DISTFACCIÓN", "DESVÍO", "SUEÑO"] },
  { w: "INTELIGENCIA", c: "ASTUCIA", f: ["TORPEZA", "NECEDAD", "SIMPLEZA"] },
  { w: "FUERZA", c: "POTENCIA", f: ["DEBILIDAD", "DESMAYO", "REPOSO"] },
  { w: "SALUD", c: "BIENESTAR", f: ["DOLENCIA", "ENFERMEDAD", "FIEBRE"] }
];

/**
 * 100 SERIES LÓGICAS PREGENERADAS
 */
export const PATTERNS_POOL = [
  // Crecientes simples
  { seq: [2, 4, 6, 8], c: 10, ops: [10, 11, 9, 12] },
  { seq: [5, 10, 15, 20], c: 25, ops: [25, 30, 24, 26] },
  { seq: [3, 6, 9, 12], c: 15, ops: [15, 16, 14, 18] },
  { seq: [4, 8, 12, 16], c: 20, ops: [20, 22, 18, 24] },
  { seq: [7, 14, 21, 28], c: 35, ops: [35, 36, 42, 34] },
  { seq: [10, 20, 30, 40], c: 50, ops: [50, 60, 45, 55] },
  { seq: [11, 22, 33, 44], c: 55, ops: [55, 66, 54, 56] },
  { seq: [1, 5, 9, 13], c: 17, ops: [17, 16, 18, 19] },
  { seq: [6, 12, 18, 24], c: 30, ops: [30, 32, 28, 36] },
  { seq: [8, 16, 24, 32], c: 40, ops: [40, 42, 38, 48] },
  { seq: [9, 18, 27, 36], c: 45, ops: [45, 46, 54, 44] },
  { seq: [15, 20, 25, 30], c: 35, ops: [35, 40, 34, 36] },
  { seq: [12, 16, 20, 24], c: 28, ops: [28, 30, 26, 32] },
  { seq: [14, 21, 28, 35], c: 42, ops: [42, 49, 40, 44] },
  { seq: [18, 24, 30, 36], c: 42, ops: [42, 44, 40, 48] },
  { seq: [21, 27, 33, 39], c: 45, ops: [45, 47, 43, 51] },
  { seq: [25, 35, 45, 55], c: 65, ops: [65, 70, 60, 75] },
  { seq: [30, 40, 50, 60], c: 70, ops: [70, 80, 65, 75] },
  { seq: [13, 17, 21, 25], c: 29, ops: [29, 31, 27, 33] },
  { seq: [19, 23, 27, 31], c: 35, ops: [35, 37, 33, 39] },
  { seq: [22, 28, 34, 40], c: 46, ops: [46, 48, 44, 52] },
  { seq: [2, 7, 12, 17], c: 22, ops: [22, 24, 21, 27] },
  { seq: [3, 11, 19, 27], c: 35, ops: [35, 37, 33, 43] },
  { seq: [4, 13, 22, 31], c: 40, ops: [40, 42, 39, 49] },
  { seq: [6, 15, 24, 33], c: 42, ops: [42, 44, 40, 51] },

  // Decrecientes simples
  { seq: [20, 18, 16, 14], c: 12, ops: [12, 10, 13, 11] },
  { seq: [50, 45, 40, 35], c: 30, ops: [30, 25, 32, 28] },
  { seq: [30, 27, 24, 21], c: 18, ops: [18, 17, 19, 15] },
  { seq: [40, 36, 32, 28], c: 24, ops: [24, 22, 26, 20] },
  { seq: [70, 63, 56, 49], c: 42, ops: [42, 35, 44, 40] },
  { seq: [100, 90, 80, 70], c: 60, ops: [60, 50, 65, 55] },
  { seq: [55, 44, 33, 22], c: 11, ops: [11, 10, 12, 0] },
  { seq: [25, 21, 17, 13], c: 9, ops: [9, 8, 10, 7] },
  { seq: [60, 54, 48, 42], c: 36, ops: [36, 34, 38, 30] },
  { seq: [80, 72, 64, 56], c: 48, ops: [48, 46, 50, 40] },
  { seq: [90, 81, 72, 63], c: 54, ops: [54, 52, 56, 45] },
  { seq: [45, 40, 35, 30], c: 25, ops: [25, 20, 26, 24] },
  { seq: [36, 32, 28, 24], c: 20, ops: [20, 18, 22, 16] },
  { seq: [42, 35, 28, 21], c: 14, ops: [14, 7, 16, 12] },
  { seq: [48, 42, 36, 30], c: 24, ops: [24, 22, 26, 18] },
  { seq: [51, 45, 39, 33], c: 27, ops: [27, 25, 29, 21] },
  { seq: [75, 65, 55, 45], c: 35, ops: [35, 30, 40, 25] },
  { seq: [80, 70, 60, 50], c: 40, ops: [40, 30, 45, 35] },
  { seq: [37, 33, 29, 25], c: 21, ops: [21, 19, 23, 17] },
  { seq: [41, 37, 33, 29], c: 25, ops: [25, 23, 27, 21] },
  { seq: [52, 46, 40, 34], c: 28, ops: [28, 26, 30, 22] },
  { seq: [32, 27, 22, 17], c: 12, ops: [12, 10, 14, 7] },
  { seq: [43, 35, 27, 19], c: 11, ops: [11, 9, 13, 3] },
  { seq: [50, 41, 32, 23], c: 14, ops: [14, 12, 16, 5] },
  { seq: [61, 52, 43, 34], c: 25, ops: [25, 23, 27, 16] },

  // Multiplicativas (Dobles, triples)
  { seq: [1, 2, 4, 8], c: 16, ops: [16, 14, 18, 32] },
  { seq: [2, 4, 8, 16], c: 32, ops: [32, 30, 34, 64] },
  { seq: [3, 6, 12, 24], c: 48, ops: [48, 46, 50, 96] },
  { seq: [1, 3, 9, 27], c: 81, ops: [81, 78, 84, 54] },
  { seq: [5, 10, 20, 40], c: 80, ops: [80, 75, 85, 160] },
  { seq: [4, 8, 16, 32], c: 64, ops: [64, 60, 68, 128] },
  { seq: [6, 12, 24, 48], c: 96, ops: [96, 90, 100, 192] },
  { seq: [2, 6, 18, 54], c: 162, ops: [162, 158, 166, 108] },
  { seq: [100, 50, 25], c: 12, ops: [12, 10, 15, 5] },
  { seq: [64, 32, 16, 8], c: 4, ops: [4, 2, 6, 0] },
  { seq: [80, 40, 20, 10], c: 5, ops: [5, 4, 6, 2] },
  { seq: [96, 48, 24, 12], c: 6, ops: [6, 4, 8, 3] },
  { seq: [72, 36, 18], c: 9, ops: [9, 8, 10, 6] },
  { seq: [48, 24, 12, 6], c: 3, ops: [3, 2, 4, 1] },
  { seq: [160, 80, 40, 20], c: 10, ops: [10, 8, 12, 5] },

  // Alternadas (+a, -b o +a, +b)
  { seq: [2, 5, 4, 7, 6], c: 9, ops: [9, 8, 10, 11] },
  { seq: [10, 15, 12, 17, 14], c: 19, ops: [19, 18, 20, 16] },
  { seq: [20, 18, 23, 21, 26], c: 24, ops: [24, 22, 25, 29] },
  { seq: [5, 10, 8, 13, 11], c: 16, ops: [16, 15, 17, 14] },
  { seq: [30, 25, 28, 23, 26], c: 21, ops: [21, 20, 22, 24] },
  { seq: [4, 8, 6, 12, 10], c: 20, ops: [20, 18, 22, 14] },
  { seq: [3, 6, 5, 10, 9], c: 18, ops: [18, 17, 19, 14] },
  { seq: [12, 14, 11, 13, 10], c: 12, ops: [12, 11, 13, 9] },
  { seq: [15, 20, 18, 23, 21], c: 26, ops: [26, 25, 27, 24] },
  { seq: [50, 40, 45, 35, 40], c: 30, ops: [30, 25, 35, 20] },
  { seq: [1, 2, 4, 5, 7], c: 8, ops: [8, 9, 10, 6] },
  { seq: [10, 12, 15, 17, 20], c: 22, ops: [22, 23, 24, 25] },
  { seq: [100, 95, 90, 85, 80], c: 75, ops: [75, 70, 80, 65] },
  { seq: [7, 9, 12, 14, 17], c: 19, ops: [19, 20, 21, 18] },
  { seq: [2, 3, 5, 8, 12], c: 17, ops: [17, 16, 18, 19] },
  { seq: [1, 3, 6, 10, 15], c: 21, ops: [21, 20, 22, 25] },
  { seq: [50, 48, 44, 38, 30], c: 20, ops: [20, 18, 22, 16] },
  { seq: [8, 11, 16, 23, 32], c: 43, ops: [43, 41, 45, 40] },
  { seq: [20, 21, 23, 26, 30], c: 35, ops: [35, 34, 36, 40] },
  { seq: [60, 59, 57, 54, 50], c: 45, ops: [45, 44, 46, 40] },

  // Series con pasos grandes / especiales
  { seq: [105, 110, 115, 120], c: 125, ops: [125, 130, 124, 126] },
  { seq: [200, 180, 160, 140], c: 120, ops: [120, 100, 130, 110] },
  { seq: [333, 444, 555, 666], c: 777, ops: [777, 888, 776, 778] },
  { seq: [120, 108, 96, 84], c: 72, ops: [72, 70, 74, 60] },
  { seq: [15, 30, 45, 60], c: 75, ops: [75, 80, 70, 90] },
  { seq: [250, 225, 200, 175], c: 150, ops: [150, 125, 160, 140] },
  { seq: [111, 222, 333, 444], c: 555, ops: [555, 666, 554, 556] },
  { seq: [5, 15, 25, 35], c: 45, ops: [45, 50, 40, 55] },
  { seq: [99, 88, 77, 66], c: 55, ops: [55, 44, 54, 56] },
  { seq: [12, 24, 36, 48], c: 60, ops: [60, 72, 58, 62] },
  { seq: [14, 28, 42, 56], c: 70, ops: [70, 84, 68, 72] },
  { seq: [16, 32, 48, 64], c: 80, ops: [80, 96, 78, 82] },
  { seq: [400, 300, 200, 100], c: 0, ops: [0, 50, 10, 25] },
  { seq: [150, 175, 200, 225], c: 250, ops: [250, 275, 240, 260] },
  { seq: [88, 77, 66, 55], c: 44, ops: [44, 33, 45, 43] }
];

/**
 * 50 FICHAS DE DOMINÓ PRECARGADAS (top: 0-6, bottom: 0-6)
 */
export const DOMINO_POOL = [
  { t: 0, b: 0 }, { t: 0, b: 1 }, { t: 0, b: 2 }, { t: 0, b: 3 }, { t: 0, b: 4 }, { t: 0, b: 5 }, { t: 0, b: 6 },
  { t: 1, b: 1 }, { t: 1, b: 2 }, { t: 1, b: 3 }, { t: 1, b: 4 }, { t: 1, b: 5 }, { t: 1, b: 6 },
  { t: 2, b: 2 }, { t: 2, b: 3 }, { t: 2, b: 4 }, { t: 2, b: 5 }, { t: 2, b: 6 },
  { t: 3, b: 3 }, { t: 3, b: 4 }, { t: 3, b: 5 }, { t: 3, b: 6 },
  { t: 4, b: 4 }, { t: 4, b: 5 }, { t: 4, b: 6 },
  { t: 5, b: 5 }, { t: 5, b: 6 },
  { t: 6, b: 6 },
  { t: 1, b: 0 }, { t: 2, b: 0 }, { t: 3, b: 0 }, { t: 4, b: 0 }, { t: 5, b: 0 }, { t: 6, b: 0 },
  { t: 2, b: 1 }, { t: 3, b: 1 }, { t: 4, b: 1 }, { t: 5, b: 1 }, { t: 6, b: 1 },
  { t: 3, b: 2 }, { t: 4, b: 2 }, { t: 5, b: 2 }, { t: 6, b: 2 },
  { t: 4, b: 3 }, { t: 5, b: 3 }, { t: 6, b: 3 },
  { t: 5, b: 4 }, { t: 6, b: 4 },
  { t: 6, b: 5 }, { t: 3, b: 5 }
];

/**
 * PAREJAS DE ELEMENTOS PARA CONTEO SELECTIVO (5x5)
 */
export const COUNT_TARGET_SETS = [
  { name: "estrellas", target: '⭐', noise: '🌙' },
  { name: "lunas", target: '🌙', noise: '⭐' },
  { name: "limones", target: '🍋', noise: '🍊' },
  { name: "naranjas", target: '🍊', noise: '🍋' },
  { name: "manzanas rojas", target: '🍎', noise: '🍏' },
  { name: "manzanas verdes", target: '🍏', noise: '🍎' },
  { name: "diamantes", target: '💎', noise: '🔷' },
  { name: "rombos azules", target: '🔷', noise: '💎' },
  { name: "coches amarillos", target: '🚕', noise: '🚗' },
  { name: "coches rojos", target: '🚗', noise: '🚕' },
  { name: "campanas sonando", target: '🔔', noise: '🔕' },
  { name: "flores de cerezo", target: '🌸', noise: '🌺' },
  { name: "corazones rojos", target: '❤️', noise: '💜' },
  { name: "corazones morados", target: '💜', noise: '❤️' },
  { name: "fresas", target: '🍓', noise: '🍒' },
  { name: "cerezas", target: '🍒', noise: '🍓' },
  { name: "fantasmas", target: '👻', noise: '💀' },
  { name: "caramelos", target: '🍬', noise: '🍭' },
  { name: "piruletas", target: '🍭', noise: '🍬' },
  { name: "balones", target: '⚽', noise: '🏀' },
  { name: "relojes de arena", target: '⏳', noise: '⌛' },
  { name: "soles", target: '☀️', noise: '⛅' }
];

/**
 * COLORES PARA EL JUEGO STROOP
 */
export const STROOP_COLORS = [
  { n: 'ROJO', h: '#e11d48' },
  { n: 'AZUL', h: '#2563eb' },
  { n: 'VERDE', h: '#16a34a' },
  { n: 'AMARILLO', h: '#d97706' }
];

export let TOTAL_LEVELS = 20;
export let CONFIG = {
  easy:   { name: "Fácil",   time: 16000, mem: 5000, speedMod: 0.7, balanceSpd: 0.45, balancePush: 10, balanceGoalMs: 1200, balanceDelayMs: 2000 },
  medium: { name: "Medio",   time: 12000, mem: 3500, speedMod: 1.0, balanceSpd: 0.75, balancePush: 9,  balanceGoalMs: 1400, balanceDelayMs: 1000 },
  hard:   { name: "Difícil", time:  8000, mem: 2000, speedMod: 1.4, balanceSpd: 1.12, balancePush: 8,  balanceGoalMs: 1500, balanceDelayMs: 500 }
};

export let TYPES = [
  'calc', 'pattern', 'anagram', 'count_target', 'antonym', 'equation_val',
  'precision_stop', 'swipe_sort', 'catch_target', 'drag_drop', 'balance',
  'sudoku_missing', 'domino_order', 'mem_seq', 'stroop', 'order_diff', 'odd_grid',
  'rps_inverted', 'memory_matrix', 'heavy_deduction'
];

export let TEXTS = {
  title: "Brain-Fit 3000",
  subtitle: "¡Entrena tu cerebro, protein free!",
  menuEasy: "🌱 Fácil",
  menuMedium: "⚡ Medio",
  menuHard: "🔥 Difícil",
  levelLabel: "Nivel",
  btnBack: "⬅ Volver al Menú",
  timeout: "⏰ ¡Tiempo agotado! (0 pts)",
  failDefault: "❌ ¡Incorrecto! Sin puntos",
  successFast: "⚡ ¡Rápido! +20 puntos",
  successNorm: "¡Correcto! +10 puntos",
  bonusTitle: "¡x2 BONUS!",
  bonusSubtitle: "+20 PUNTOS",
  bonusDesc: "¡Súper rápido! (< {seconds}s)",
  finalScoreTitle: "PUNTUACIÓN FINAL",
  btnChangeDiff: "Cambiar de dificultad",
  endPerfectHardTitle: "¡CAMPEÓN DE CAMPEONES!",
  endPerfectHardMsg: "¡Increíble! Has conseguido la puntuación perfecta ({score}/{max}) en el nivel <strong>Difícil</strong>. ¡Eres el número uno indiscutible!",
  btnPerfectHard: "👑 Revalidar título",
  endPerfectNextTitle: "¡PUNTUACIÓN PERFECTA!",
  endPerfectNextMsg: "¡Brillante! Has obtenido el máximo posible de {score} puntos en nivel <strong>{diff}</strong>. ¡Estás listo para dar el salto al nivel <strong>{nextDiff}</strong>!",
  btnPerfectNext: "🚀 Pasar al nivel {nextDiff}",
  endNearPerfectTitle: "¡CASI PERFECTO!",
  endNearPerfectHardMsg: "¡Extraordinario resultado! Te has quedado muy cerca de la perfección en el nivel <strong>Difícil</strong>. ¡Falta muy poco para coronarte como Campeón de Campeones!",
  endNearPerfectMsg: "¡Gran partida! Te has quedado muy cerca de la máxima puntuación en nivel <strong>{diff}</strong>. ¡Un pequeño empujón más y pasarás al nivel <strong>{nextDiff}</strong>!",
  btnTryMax: "🔁 ¡Intentar el máximo!",
  endGoodTrainingTitle: "¡BUEN ENTRENAMIENTO!",
  endGoodTrainingMsg: "Has completado las {levels} pruebas en nivel <strong>{diff}</strong>. ¡Sigue practicando para mejorar tu agilidad mental y conseguir más puntos de bonificación rápida!",
  btnRepeatLevel: "Repetir nivel",

  rpsTitleWin: "Elige para <span style=\"color:#16a34a;background:#dcfce7;padding:2px 8px;border-radius:8px;\">GANAR</span> a:",
  rpsTitleLose: "Elige para <span style=\"color:#e11d48;background:#ffe4e6;padding:2px 8px;border-radius:8px;\">PERDER</span> contra:",
  rpsFail: "❌ Jugada incorrecta",
  matrixTitle: "Memoriza las celdas ({seconds}s):",
  matrixPlayTitle: "Toca las celdas marcadas:",
  matrixFail: "❌ Celda incorrecta",
  heavyTitle: "¿Cuál es MÁS pesado?",
  heavyTitleMore: "¿Cuál es MÁS pesado?",
  heavyTitleLess: "¿Cuál es MENOS pesado?",
  heavyFail: "❌ Deducción incorrecta",

  calcTitle: "Resuelve:",
  memTitle: "Memoriza el orden ({seconds}s):",
  memPlayTitle: "Toca en orden:",
  memFail: "❌ Secuencia incorrecta",
  stroopInkPrompt: "Toca el color de la <span style=\"color:#0284c7;background:#e0f2fe;padding:2px 8px;border-radius:8px;\">TINTA</span>:",
  stroopWordPrompt: "Toca lo que <span style=\"color:#059669;background:#ecfdf5;padding:2px 8px;border-radius:8px;\">DICE LA PALABRA</span>:",
  stroopFail: "❌ Color incorrecto",
  orderDesc: "MAYOR a MENOR",
  orderAsc: "MENOR a MAYOR",
  orderTitle: "Ordena de <span style=\"color:#d97706\">{order}</span>:",
  orderFail: "❌ Orden incorrecto",
  oddGridTitle: "Encuentra el diferente:",
  patternTitle: "Completa la serie:",
  anagramTitle: "¿Qué palabra es?",
  countTargetTitle: "Cuenta los/las <span style=\"color:#db2777;text-decoration:underline;\">{label}</span> (<span style=\"font-size:28px\">{target}</span>):",
  antonymPrompt: "Toca el <span style=\"color:#e11d48;background:#fff1f2;padding:2px 8px;border-radius:8px;\">ANTÓNIMO</span> de:",
  synonymPrompt: "Toca el <span style=\"color:#059669;background:#ecfdf5;padding:2px 8px;border-radius:8px;\">SINÓNIMO</span> de:",
  equationTitle: "¿Es correcta la igualdad?",
  btnYes: "✔ SÍ",
  btnNo: "✖ NO",
  precisionTitle: "Detén la barra en la zona verde:",
  btnStop: "¡PARAR!",
  precisionFail: "❌ Fuera de la zona",
  swipeTitle: "Clasifica rápido:",
  btnFruit: "⬅️ Fruta",
  btnAnimal: "Animal ➡️",
  swipeFail: "❌ Categoría incorrecta",
  catchTitle: "¡Atrapa la burbuja!",
  dragTitle: "Encaja en su lugar:",
  balanceTitle: "Mantén el equilibrio:",
  btnBalancePush: "EMPUJAR ARRIBA",
  balanceFail: "❌ Perdiste el equilibrio",
  sudokuTitle: "¿Qué número falta en el cuadrante?",
  sudokuFail: "❌ Número incorrecto",
  dominoTitle: "Ordena las fichas de dominó:",
  dominoOrderDesc: "MAYOR a MENOR (Descendente)",
  dominoOrderAsc: "MENOR a MAYOR (Ascendente)",
  dominoFail: "❌ Orden de fichas incorrecto"
};

export async function loadAppConfig() {
  try {
    const res = await fetch('./config.json');
    if (res.ok) {
      const json = await res.json();
      if (json.difficulties) Object.assign(CONFIG, json.difficulties);
      if (json.games_enabled) {
        TYPES = Object.keys(json.games_enabled).filter(k => json.games_enabled[k]);
      }
      if (json.ui_texts) Object.assign(TEXTS, json.ui_texts);
      TOTAL_LEVELS = TYPES.length;
    }
  } catch (err) {
    console.warn('Config not found or error, using defaults', err);
  }
}
