name: Unit Tests

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - 'brainfit/**'
      - 'murmeteo/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ "main", "master" ]
    paths:
      - 'brainfit/**'
      - 'murmeteo/**'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    - name: Run Brainfit Tests
      if: hashFiles('brainfit/package.json') != ''
      working-directory: brainfit
      run: |
        npm install
        npm run test || true
    - name: Run MurMeteo Tests
      if: hashFiles('murmeteo/package.json') != ''
      working-directory: murmeteo
      run: npm run test
