name: Unit Tests

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - 'brainfit/**'
      - 'murmeteo/**'
      - 'loopp/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ "main", "master" ]
    paths:
      - 'brainfit/**'
      - 'murmeteo/**'
      - 'loopp/**'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Filter modified paths
      uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          workflows:
            - '.github/workflows/**'
          brainfit:
            - 'brainfit/**'
          murmeteo:
            - 'murmeteo/**'
          loopp:
            - 'loopp/**'

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - name: Run Brainfit Tests
      if: (steps.filter.outputs.brainfit == 'true' || steps.filter.outputs.workflows == 'true') && hashFiles('brainfit/package.json') != ''
      working-directory: brainfit
      run: |
        npm install
        npm run test || true

    - name: Run MurMeteo Tests
      if: (steps.filter.outputs.murmeteo == 'true' || steps.filter.outputs.workflows == 'true') && hashFiles('murmeteo/package.json') != ''
      working-directory: murmeteo
      run: npm run test

    - name: Run Loopp Tests
      if: (steps.filter.outputs.loopp == 'true' || steps.filter.outputs.workflows == 'true') && hashFiles('loopp/package.json') != ''
      working-directory: loopp
      run: |
        npm ci || npm install
        npx playwright install --with-deps chromium
        npm run test
